USE quanly;

DROP TABLE IF EXISTS Class;
DROP TABLE IF EXISTS Teacher;

CREATE TABLE Class (
 id INT PRIMARY KEY,
 name VARCHAR(50)
);

CREATE TABLE Teacher (
 id INT PRIMARY KEY,
 name VARCHAR(50),
 age INT,
 country VARCHAR(50)
);
SHOW TABLES;